on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4 

    - run: |
        echo "Checking .opentofu-version file:"
        ls -la .opentofu-version
        cat .opentofu-version
    - name: Install OpenTofu with Version from .opentofu-version
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version_file: .opentofu-version
      env:
        ACTIONS_STEP_DEBUG: true
   
    - run: tofu --version